### ISSUE TITLE
自己部署的不能双击打开office文件

### ISSUE THREAD

**Issue by fengdu126** [jamebal/jmal-cloud-server#157]
我看demo网站是可以双击打开excel或者word文件，请问下这个还需要什么特别配置吗?

![Uploading image.png…]()

**Comment by jamebal** [comment]
只要`docker-compose.yml`里面包含了office就行: 
```yml
office: # Optional
    container_name: jmalcloud_office
    image: onlyoffice/documentserver:8.0.1
    environment:
      TZ: "Asia/Shanghai"
      JWT_SECRET: "my_secret"
    restart: unless-stopped
```
