### ISSUE TITLE
可以直接运行docker compsoe.yml吗？

### ISSUE THREAD

**Issue by kokojacket** [jamebal/jmal-cloud-server#35]
可以直接运行docker compsoe.yml吗？还是必须使用.sh来执行？

**Comment by jamebal** [comment]
目前直接运行docker compsoe.yml会有问题

**Comment by kokojacket** [comment]
好的，我的nas是威联通，没有git，也可以直接下载整个项目，然后执行sh对吧

**Comment by jamebal** [comment]
是的

**Comment by jamebal** [comment]
下个版本优化下,直接运行docker compsoe.yml

**Comment by kokojacket** [comment]
感谢~！，大佬快出文件素材打标签和标签搜索功能呀，你是我的神~~~

**Comment by jamebal** [comment]
标签功能没那么快😂

**Comment by kokojacket** [comment]
好吧，我是一名剪辑师，我觉得您这个项目非常符合我的需求。大佬加油~~！！。我就缺标签了😂😂

**Comment by kokojacket** [comment]
@jamebal 我现在已经通过.sh安装完成并进入网盘，是不是可以compsoe down然后通过修改docker-compose.yml，来添加本地文件挂载目录到网盘？

**Comment by jamebal** [comment]
可以执行`./jc.sh uninstall`卸载, 再修改`.env`文件, 其中: `RESOURCE_DB_PATH`为数据库存储位置, `RESOURCE_FILE_PATH`为文件存储位置

**Comment by kokojacket** [comment]
好的

**Comment by kokojacket** [comment]
2.6.8支持一键运行吗？

**Comment by jamebal** [comment]
感谢反馈, 暂不支持直接运行docker compsoe.yml, 等支持了您会收到通知

**Comment by jamebal** [comment]
现在可以直接运行`docker compsoe.yml`了
1. 创建文件夹并进入
```shell
mkdir jmalcloud
cd jmalcloud
```
2. 创建文件`docker-cmpose.yml`
docker-cmpose.yml文件内容可直接复制自[docker-compose.example.yml](https://github.com/jamebal/jmal-cloud-server/blob/master/docker-compose.example.yml), 无需修改
3. 创建文件`.env`
.evn文件内容可参考[.env-example](https://github.com/jamebal/jmal-cloud-server/blob/master/.env-example)
一般只需修改两处:
`RESOURCE_DB_PATH`: 文件库文件位置
`RESOURCE_FILE_PATH`: 网盘文件位置
4. 运行
```shell
docker compose up -d
```

**Comment by kokojacket** [comment]
！！！赞！大佬开个交流群吧。摸鱼

**Comment by kokojacket** [comment]
> `RESOURCE_DB_PATH`: 数据库文件位置

.env是不是也可以直接写在compose.yml中而不是另外新建文件？
RESOURCE_DB_PATH: 数据库文件位置
RESOURCE_FILE_PATH: 网盘文件位置
这两处位置说的是宿主机上的路径吧？

**Comment by jamebal** [comment]
改改compose.yml也可以不用.env

**Comment by jamebal** [comment]
> > `RESOURCE_DB_PATH`: 数据库文件位置
> 
> .env是不是也可以直接写在compose.yml中而不是另外新建文件？ RESOURCE_DB_PATH: 数据库文件位置 RESOURCE_FILE_PATH: 网盘文件位置 这两处位置说的是宿主机上的路径吧？

是的

**Comment by kokojacket** [comment]
[docker-compose.example.yml](https://github.com/jamebal/jmal-cloud-server/blob/master/docker-compose.example.yml)
这里面jmalcloud_server和nginx都给了prots,似乎应该只给nginx prots就好了吧。

**Comment by jamebal** [comment]
> [docker-compose.example.yml](https://github.com/jamebal/jmal-cloud-server/blob/master/docker-compose.example.yml) 这里面jmalcloud_server和nginx都给了prots,似乎应该只给nginx prots就好了吧。

是的

**Comment by jamebal** [comment]
这是最精简的docker-compose.yml
```yml
version: "3"
services:
  jmalcloud:
    container_name: jmalcloud_server
    image: jmal/jmalcloud:latest
    environment:
      MONGODB_URI: mongodb://mongo:27017/jmalcloud
      TZ: Asia/Shanghai
    volumes:
      - ./docker/jmalcloud/files:/jmalcloud/files/
    restart: unless-stopped
  mongo:
    container_name: jmalcloud_mongodb
    image: mongo:4.4
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./docker/jmalcloud/mongodb/data/db:/data/db
    restart: unless-stopped
    command: --wiredTigerCacheSizeGB 0.5
  nginx:
    container_name: jmalcloud_nginx
    image: jmal/jmalcloud-nginx:latest
    ports:
      - 7070:80
      - 7071:8089
    environment:
      TZ: Asia/Shanghai
    links:
      - jmalcloud
      - office
      - drawio-webapp
    restart: unless-stopped
  office: # 可选
    container_name: jmalcloud_office
    image: onlyoffice/documentserver:7.0.0.132
    environment:
      TZ: Asia/Shanghai
    restart: unless-stopped
  drawio-webapp: # 可选
    container_name: jmalcloud_drawio
    image: jgraph/drawio:20.2.3
    environment:
      TZ: Asia/Shanghai
    restart: unless-stopped

```
